import http from 'k6/http';

/**
 * Authenticate using OAuth against IdentityServer
 * @function
 * @param  {string} identityServerUrl - IdentityServer url to authenticate against
 * @param  {string} clientId - Generated by IdentityServer automatically
 * @param  {string} scope - Space-separated list of scopes
 * @param  {string|object} resource - Either a resource ID (as string) or an object containing username and password
 */
export function authenticateUsingIdentityServer(
  identityServerUrl,
  clientId,
  scope,
  resource
) {
  const url = `https://${identityServerUrl}/identity/connect/token`;
  const requestBody = { 
    scope: scope,
    grant_type: 'password',
    username: resource.username,
    password: resource.password,
    client_id: clientId
  };

  return http.post(url, requestBody).json();
}
